### ISSUE TITLE
Finish multi-user support

### ISSUE THREAD

**Issue by bojanrajkovic** [bojanrajkovic/Volley#13]
I started stubbing out some multi-user support in https://github.com/bojanrajkovic/Volley/commit/0fe4dc007e0c9569bca90fc191fa2986ceb5b1bf, but I never really finished it, at least not in terms of actually implementing the rest (database-backed access control, initial setup, etc.).

- [x] Database-backed access control implementation [#19]
- [x] Configurable storage of data protection keys: on-machine or in Redis. [#24]
  1. Need Redis for synchronized storage between multiple workers.
  2. Key _encryption_?
- [x] Bootstrap initial user [#25]
  1. Bootstrap the user by asking for the username and generating an API key
  2. Only attempt bootstrap if access control is database-backed&mdash;if it's config-file backed,
      we can't bootstrap new users.
- [x] Migrate any already-uploaded files to the initial user [#25]
  1. If we're config-file backed, migrate files to the first admin user defined.
- [x] Update files table to connect file to owner (add `OwnerId` column?) [#22]
- [x] Update controllers to generate URLs with the user and file name [#23]

**Comment by bojanrajkovic** [comment]
Fully fixed by #19, #22, #23, and #25.
